# Generated by Django 5.0.4 on 2024-04-24 14:55

import app.models.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(app.models.core.Invoice.Statuses['open'], app.models.core.Invoice.Statuses['open']), (app.models.core.Invoice.Statuses['pending'], app.models.core.Invoice.Statuses['pending']), (app.models.core.Invoice.Statuses['paid'], app.models.core.Invoice.Statuses['paid']), (app.models.core.Invoice.Statuses['completed'], app.models.core.Invoice.Statuses['completed'])], default=app.models.core.Invoice.Statuses['open'], max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(app.models.core.Payment.Statuses['pending'], app.models.core.Payment.Statuses['pending']), (app.models.core.Payment.Statuses['cancelled'], app.models.core.Payment.Statuses['cancelled']), (app.models.core.Payment.Statuses['completed'], app.models.core.Payment.Statuses['completed'])], default=app.models.core.Payment.Statuses['pending'], max_length=64),
        ),
    ]
