# Generated by Django 5.0.4 on 2024-04-20 18:45

import app.models.core
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_count',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[(app.models.core.Settings.Currencies['euro'], app.models.core.Settings.Currencies['euro']), (app.models.core.Settings.Currencies['usd'], app.models.core.Settings.Currencies['usd'])], default=app.models.core.Settings.Currencies['euro'], max_length=16),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('edit_timestamp', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=32)),
                ('method', models.CharField(choices=[(app.models.core.Payment.Methods['cash'], app.models.core.Payment.Methods['cash']), (app.models.core.Payment.Methods['stripe'], app.models.core.Payment.Methods['stripe'])], max_length=64)),
                ('status', models.CharField(choices=[(app.models.core.Payment.Statuses['pending'], app.models.core.Payment.Statuses['pending']), (app.models.core.Payment.Statuses['cancelled'], app.models.core.Payment.Statuses['cancelled']), (app.models.core.Payment.Statuses['completed'], app.models.core.Payment.Statuses['completed'])], max_length=64)),
                ('gateway_id', models.CharField(blank=True, max_length=256, null=True)),
                ('gateway_url', models.URLField(blank=True, max_length=512, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
