# Generated by Django 5.0.4 on 2024-04-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_invoice_items_count_invoice_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
