# Generated by Django 5.0.4 on 2024-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_invoice_checkout_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
